Server:
  Mode: debug # debug | release
  Port: :8765
  DbType: "mysql" # mysql | sqlite
  DbAutoMigrate: true # 是否自动迁移数据库表结构 (表结构没变可以不迁移, 提高启动速度)
  DbLogMode: "error" # 日志级别 silent, error, warn, info, 默认 info
JWT:
  Secret: "abc123321"
  Expire: 24 # hour
  Issuer: "computer_store"
Mysql:
  Host: "127.0.0.1"
  Port: "3306"
  Config: "charset=utf8mb4&parseTime=True&loc=Local" # 其他配置, 例如时区
  Dbname: "c_m"
  Username: "root"
  Password: "YZN700563a"
Redis:
  DB: 7
  Addr: '127.0.0.1:6379'
  Password: ''
Session:
  Name: "mysession"
  Salt: "salt"
  MaxAge: 600 # second
Log:
  Level: "debug" # debug | info | warn | error
  Format: "text" # text | json
  Directory: "log"